name: aeg_portfolio
favicon: null
layout_spectrum: 0.5232792908791453
typography_spectrum: 0.6892285691574216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01feea'
    - '#0087b7'
    - '#00b7c6'
    - '#00527a'
    - '#c3fef3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
