name: aeg_portfolio
favicon: null
layout_spectrum: 0.5232792908791453
typography_spectrum: 0.6892285691574216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8570613809861243
  lightness: 0.9032306622248143
  saturation: 0.450324862729758
  rhythmicContrast: 0.47090784809552133
purpose: []
